//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPU.Sources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KPCapture.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The decrypt script is applied.
        ///Script name : {0}.
        /// </summary>
        internal static string DECRYPT_APPLIED_DESCRIPTION {
            get {
                return ResourceManager.GetString("DECRYPT_APPLIED_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decryption script has been successfully applied..
        /// </summary>
        internal static string DECRYPT_APPLY_SUCCESSFUL {
            get {
                return ResourceManager.GetString("DECRYPT_APPLY_SUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The decryption script has been cleared..
        /// </summary>
        internal static string DECRYPT_CLEAR_SUCCESSFUL {
            get {
                return ResourceManager.GetString("DECRYPT_CLEAR_SUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your python script for decryption.
        ///Function &apos;decrypt&apos; in your python script file will decrypt data.
        ///Follow the prototype : 
        ///
        ///def decrypt(bytes):
        ///    do...
        ///    return newBytes.
        /// </summary>
        internal static string DECRYPT_DESCRIPTION {
            get {
                return ResourceManager.GetString("DECRYPT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name(pid).
        /// </summary>
        internal static string DEFAULT_PROCESS_NAME {
            get {
                return ResourceManager.GetString("DEFAULT_PROCESS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State : .
        /// </summary>
        internal static string DEFAULT_PROCESS_STATEMENT {
            get {
                return ResourceManager.GetString("DEFAULT_PROCESS_STATEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission : .
        /// </summary>
        internal static string DEFAULT_PROCESS_TRANSMISSION {
            get {
                return ResourceManager.GetString("DEFAULT_PROCESS_TRANSMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use filter : .
        /// </summary>
        internal static string DEFAULT_PROCESS_USEFILTER {
            get {
                return ResourceManager.GetString("DEFAULT_PROCESS_USEFILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DetailIcon {
            get {
                object obj = ResourceManager.GetObject("DetailIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State : {0}.
        /// </summary>
        internal static string FORMAT_PROCESS_STATE {
            get {
                return ResourceManager.GetString("FORMAT_PROCESS_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission : {0} / {1}.
        /// </summary>
        internal static string FORMAT_PROCESS_TRANSMISSION {
            get {
                return ResourceManager.GetString("FORMAT_PROCESS_TRANSMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use filter : {0}.
        /// </summary>
        internal static string FORMAT_PROCESS_USEFILTER {
            get {
                return ResourceManager.GetString("FORMAT_PROCESS_USEFILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFINITE.
        /// </summary>
        internal static string INFINITE {
            get {
                return ResourceManager.GetString("INFINITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KPCapture {
            get {
                object obj = ResourceManager.GetObject("KPCapture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set filter during capturing packet.
        ///Please pause capture and try again..
        /// </summary>
        internal static string MSG_CANNOT_SET_FILTER_DURING_RUNNING {
            get {
                return ResourceManager.GetString("MSG_CANNOT_SET_FILTER_DURING_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same filter already exists..
        /// </summary>
        internal static string MSG_FILTER_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("MSG_FILTER_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the hexadecimal format
        ///Example) 01 AA B1 DC 10 DD.
        /// </summary>
        internal static string MSG_INVALID_HEXSTR_FORMAT {
            get {
                return ResourceManager.GetString("MSG_INVALID_HEXSTR_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the value of IP and port.
        ///
        ///Example) 192.168.0.1:9998.
        /// </summary>
        internal static string MSG_INVALID_IP_FORMAT {
            get {
                return ResourceManager.GetString("MSG_INVALID_IP_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check that input size is a number.
        /// </summary>
        internal static string MSG_INVALID_NUMBER_FORMAT {
            get {
                return ResourceManager.GetString("MSG_INVALID_NUMBER_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data transmission.
        /// </summary>
        internal static string MSG_NO_TRANSMISSION_HISTORY {
            get {
                return ResourceManager.GetString("MSG_NO_TRANSMISSION_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter one or more filters.
        ///None filter has not been entered..
        /// </summary>
        internal static string MSG_NOT_ENOUGH_FILTER_INFORMATION {
            get {
                return ResourceManager.GetString("MSG_NOT_ENOUGH_FILTER_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The problem occurred while adding a channel.
        ///Please try again..
        /// </summary>
        internal static string MSG_OCCURRED_DURING_ADD_CHANNEL {
            get {
                return ResourceManager.GetString("MSG_OCCURRED_DURING_ADD_CHANNEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find &apos;decrypt&apos; function in your python script.
        ///Please check &apos;decrypt&apos; function is exist again..
        /// </summary>
        internal static string NOT_FOUND_DECRYPT_ROUTINE {
            get {
                return ResourceManager.GetString("NOT_FOUND_DECRYPT_ROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find file : {0}
        ///Please check your python script path again..
        /// </summary>
        internal static string NOT_FOUND_SCRIPT {
            get {
                return ResourceManager.GetString("NOT_FOUND_SCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string NOTIFICATION {
            get {
                return ResourceManager.GetString("NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end.
        /// </summary>
        internal static string PACKET_ENDMARK {
            get {
                return ResourceManager.GetString("PACKET_ENDMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cshyeon.
        /// </summary>
        internal static string PACKET_MAGIC_SIGNATURE {
            get {
                return ResourceManager.GetString("PACKET_MAGIC_SIGNATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap python {
            get {
                object obj = ResourceManager.GetObject("python", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string STATE_PAUSE {
            get {
                return ResourceManager.GetString("STATE_PAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string STATE_RUNNING {
            get {
                return ResourceManager.GetString("STATE_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unusing.
        /// </summary>
        internal static string STATE_UNUSING {
            get {
                return ResourceManager.GetString("STATE_UNUSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using.
        /// </summary>
        internal static string STATE_USING {
            get {
                return ResourceManager.GetString("STATE_USING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error
        ///
        ///Line : {0} Column : {1}
        ///Error code : {2}.
        /// </summary>
        internal static string SYNTAX_ERROR {
            get {
                return ResourceManager.GetString("SYNTAX_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string TEXT_DELETE_BUTTON {
            get {
                return ResourceManager.GetString("TEXT_DELETE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string TEXT_DETAIL_BUTTON {
            get {
                return ResourceManager.GetString("TEXT_DETAIL_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string TEXT_FILTER_BUTTON {
            get {
                return ResourceManager.GetString("TEXT_FILTER_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string TEXT_PAUSE_BUTTON {
            get {
                return ResourceManager.GetString("TEXT_PAUSE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string TEXT_RUN_BUTTON {
            get {
                return ResourceManager.GetString("TEXT_RUN_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string TEXT_STATE_BUTTON {
            get {
                return ResourceManager.GetString("TEXT_STATE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused.
        /// </summary>
        internal static string UNUSED {
            get {
                return ResourceManager.GetString("UNUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        internal static string USED {
            get {
                return ResourceManager.GetString("USED", resourceCulture);
            }
        }
    }
}
